# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/proto/hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi/proto/hello.proto\x12\x05proto\"\x1d\n\x0cHelloRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1f\n\rHelloResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2;\n\x05Hello\x12\x32\n\x05Hello\x12\x13.proto.HelloRequest\x1a\x14.proto.HelloResponseB\x04Z\x02./b\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLORESPONSE = DESCRIPTOR.message_types_by_name['HelloResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'api.proto.hello_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'api.proto.hello_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

_HELLO = DESCRIPTOR.services_by_name['Hello']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _HELLOREQUEST._serialized_start=32
  _HELLOREQUEST._serialized_end=61
  _HELLORESPONSE._serialized_start=63
  _HELLORESPONSE._serialized_end=94
  _HELLO._serialized_start=96
  _HELLO._serialized_end=155
# @@protoc_insertion_point(module_scope)
